branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "build"
          - "test"
          - "lint"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      restrictions: null  # No restrictions on who can push to this branch
      
  - name: develop
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "build"
          - "test"
          - "lint"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      restrictions: null  # No restrictions on who can push to this branch
