# Generated by Django 4.2.7 on 2024-12-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_sample_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
