# Generated by Django 4.2.7 on 2024-12-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cbd_content",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="product",
            name="thc_content",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
