# Generated by Django 4.2.7 on 2024-12-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_product_cbd_content_alter_product_thc_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="CBDEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="effects",
        ),
        migrations.AddField(
            model_name="product",
            name="effects",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.cbdeffect"
            ),
        ),
    ]
