# Generated by Django 4.2.9 on 2024-12-27 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpreferences",
            options={
                "verbose_name": "user preference",
                "verbose_name_plural": "user preferences",
            },
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="order_updates_notifications",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="promotions_notifications",
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="loyalty_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="loyalty_tier",
            field=models.CharField(
                choices=[
                    ("BRONZE", "Bronze"),
                    ("SILVER", "Silver"),
                    ("GOLD", "Gold"),
                    ("PLATINUM", "Platinum"),
                ],
                default="BRONZE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="newsletter",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="order_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="promotional_emails",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="push_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="show_last_seen",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="show_online_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="show_profile_photo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("system", "System Default"),
                ],
                default="system",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="currency",
            field=models.CharField(
                choices=[
                    ("KES", "Kenyan Shilling"),
                    ("UGX", "Ugandan Shilling"),
                    ("TZS", "Tanzanian Shilling"),
                    ("USD", "US Dollar"),
                ],
                default="KES",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("sw", "Swahili")],
                default="en",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("PROFILE_UPDATE", "Profile Update"),
                            ("ORDER_PLACED", "Order Placed"),
                            ("REVIEW_POSTED", "Review Posted"),
                            ("POINTS_EARNED", "Points Earned"),
                            ("POINTS_REDEEMED", "Points Redeemed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_info", models.JSONField(blank=True, null=True)),
                ("location", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user activity",
                "verbose_name_plural": "user activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecuritySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("two_factor_enabled", models.BooleanField(default=False)),
                (
                    "two_factor_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SMS", "SMS"),
                            ("EMAIL", "Email"),
                            ("APP", "Authenticator App"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("login_alerts", models.BooleanField(default=True)),
                ("trusted_devices", models.JSONField(default=list)),
                ("last_password_change", models.DateTimeField(auto_now_add=True)),
                ("password_reset_required", models.BooleanField(default=False)),
                (
                    "account_recovery_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "account_recovery_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("FACEBOOK", "Facebook"),
                            ("GOOGLE", "Google"),
                            ("APPLE", "Apple"),
                            ("TWITTER", "Twitter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("platform_user_id", models.CharField(max_length=255)),
                (
                    "platform_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "social connection",
                "verbose_name_plural": "social connections",
                "unique_together": {("user", "platform", "platform_user_id")},
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_used", models.CharField(max_length=10)),
                ("points_awarded", models.IntegerField(default=0)),
                ("is_successful", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "referred_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referred_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "referral",
                "verbose_name_plural": "referrals",
                "unique_together": {("referrer", "referred_user")},
            },
        ),
    ]
