# Generated by Django 4.2.9 on 2024-12-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_remove_userpreferences_currency_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verificationcode",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="verificationcode",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="verificationcode",
            name="identifier",
        ),
        migrations.RemoveField(
            model_name="verificationcode",
            name="type",
        ),
        migrations.RemoveField(
            model_name="verificationcode",
            name="user",
        ),
        migrations.AddField(
            model_name="verificationcode",
            name="phone_number",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="verificationcode",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
