# Generated by Django 4.2.7 on 2024-12-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0007_alter_address_options_alter_userpreferences_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="phone number",
            ),
        ),
    ]
