# Generated by Django 4.2.7 on 2024-12-27 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0008_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationcode",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
