# Generated by Django 4.2.7 on 2024-12-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_verificationcode_expires_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(
                fields=["email", "code", "is_used"], name="authenticat_email_c74da5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(
                fields=["email", "is_used", "expires_at"],
                name="authenticat_email_bbcb05_idx",
            ),
        ),
    ]
