# Generated by Django 4.2.7 on 2024-12-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0010_verificationcode_authenticat_email_c74da5_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verificationcode",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "verification code",
                "verbose_name_plural": "verification codes",
            },
        ),
        migrations.AlterField(
            model_name="verificationcode",
            name="code",
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="verificationcode",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="verificationcode",
            name="expires_at",
            field=models.DateTimeField(),
        ),
    ]
